<a href="https://colab.research.google.com/github/netoquimico/Pythonworks/blob/main/Classification_mushrooms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [39]:
mushrooms=pd.read_csv('/content/mushrooms.csv')

In [40]:
mushrooms


class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [41]:
mushrooms.dtypes

class                       object
cap-shape                   object
cap-surface                 object
cap-color                   object
bruises                     object
odor                        object
gill-attachment             object
gill-spacing                object
gill-size                   object
gill-color                  object
stalk-shape                 object
stalk-root                  object
stalk-surface-above-ring    object
stalk-surface-below-ring    object
stalk-color-above-ring      object
stalk-color-below-ring      object
veil-type                   object
veil-color                  object
ring-number                 object
ring-type                   object
spore-print-color           object
population                  object
habitat                     object
dtype: object

In [42]:
mushrooms.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [43]:
from sklearn.preprocessing import LabelEncoder

In [44]:
encoder = LabelEncoder()

In [45]:
mushrooms['class'] = encoder.fit_transform(mushrooms['class'])
mushrooms['cap-shape'] = encoder.fit_transform(mushrooms['cap-shape'])
mushrooms['cap-surface'] = encoder.fit_transform(mushrooms['cap-surface'])
mushrooms['cap-color'] = encoder.fit_transform(mushrooms['cap-color'])
mushrooms['bruises'] = encoder.fit_transform(mushrooms['bruises'])
mushrooms['odor'] = encoder.fit_transform(mushrooms['odor'])
mushrooms['gill-attachment'] = encoder.fit_transform(mushrooms['gill-attachment'])
mushrooms['gill-spacing'] = encoder.fit_transform(mushrooms['gill-spacing'])
mushrooms['gill-size'] = encoder.fit_transform(mushrooms['gill-size'])
mushrooms['gill-color'] = encoder.fit_transform(mushrooms['gill-color'])
mushrooms['stalk-shape'] = encoder.fit_transform(mushrooms['stalk-shape'])
mushrooms['stalk-root'] = encoder.fit_transform(mushrooms['stalk-root'])
mushrooms['stalk-surface-above-ring'] = encoder.fit_transform(mushrooms['stalk-surface-above-ring'])
mushrooms['stalk-surface-below-ring'] = encoder.fit_transform(mushrooms['stalk-surface-below-ring'])
mushrooms['stalk-color-above-ring'] = encoder.fit_transform(mushrooms['stalk-color-above-ring'])
mushrooms['stalk-color-below-ring'] = encoder.fit_transform(mushrooms['stalk-color-below-ring'])
mushrooms['veil-type'] = encoder.fit_transform(mushrooms['veil-type'])
mushrooms['veil-color'] = encoder.fit_transform(mushrooms['veil-color'])
mushrooms['ring-number'] = encoder.fit_transform(mushrooms['ring-number'])
mushrooms['ring-type'] = encoder.fit_transform(mushrooms['ring-type'])
mushrooms['spore-print-color'] = encoder.fit_transform(mushrooms['spore-print-color'])
mushrooms['population'] = encoder.fit_transform(mushrooms['population'])
mushrooms['habitat'] = encoder.fit_transform(mushrooms['habitat'])

In [46]:
mushrooms


class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                   1             0          0           5  ...   
3                   1             0          1           5  ...   
4                   1             1          0           4  ...   
...               ...           ...        ...         ...  ...   
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 23 columns]

# **Divisão entre previsores e classes**

In [47]:
y_mushrooms =mushrooms.iloc[:,0].values

In [48]:
y_mushrooms

array([1, 0, 0, ..., 0, 1, 0])

In [49]:
x_mushrooms =mushrooms.iloc[:,1:24].values

In [50]:
x_mushrooms.shape

(8124, 22)

# **Divisão da base de treinamento e teste**

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
SEED = 20

In [53]:
x_mushrooms_training, x_mushrooms_test, y_mushrooms_training, y_mushrooms_test = train_test_split(x_mushrooms, y_mushrooms, test_size = 0.25, random_state = SEED, stratify = y_mushrooms)

In [54]:
x_mushrooms_training.shape

(6093, 22)

In [55]:
x_mushrooms_test.shape

(2031, 22)

# **Naive Bayes**

In [56]:
from sklearn.naive_bayes import GaussianNB

In [59]:
mushroomsmodel = GaussianNB()

mushroomsmodel.fit(x_mushrooms_training,y_mushrooms_training)

GaussianNB()

In [60]:
previsoes=mushroomsmodel.predict(x_mushrooms_test)

In [61]:
previsoes

array([1, 1, 0, ..., 1, 1, 0])

In [62]:
y_mushrooms_test

array([1, 0, 0, ..., 1, 1, 0])

In [63]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [64]:
accuracy_score(y_mushrooms_test, previsoes)

0.9212210733628754

# **modelo SVC**

In [65]:
from sklearn.svm import LinearSVC

In [66]:
mushroomsmodel = LinearSVC()

In [67]:
mushroomsmodel.fit(x_mushrooms_training,y_mushrooms_training)

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [68]:
previsoes=mushroomsmodel.predict(x_mushrooms_test)

In [69]:
accuracy_score(y_mushrooms_test, previsoes)

0.9448547513540128